# -*- coding: utf-8 -*-
"""ViLT_StreamlitApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5remCmjf9-Xb0MTg3UyUMUYR4ud8Toc
"""

#!pip install streamlit

import PIL
import transformers as tf
import torch
import requests
from io import BytesIO
from PIL import Image
from transformers import ViltProcessor,ViltForQuestionAnswering
import streamlit as st

# vilt code
processor=ViltProcessor.from_pretrained("dandelin/vilt-b32-finetuned-vqa")
model=ViltForQuestionAnswering.from_pretrained("dandelin/vilt-b32-finetuned-vqa")

def get_answer(image,text):
  # load image
  img=Image.open(BytesIO(image)).convert('RGB')

  # prepare inputs
  encoding = processor(img, text, return_tensors="pt")

  # forward pass
  outputs = model(**encoding)
  logits = outputs.logits
  idx = logits.argmax(-1).item()

  # get predicted answer
  answer = model.config.id2label[idx]
  return answer


# Streamlit app
def main():
    st.title("Vilt Question Answering App")

    # Upload image
    uploaded_image = st.file_uploader("Upload Image", type=["jpg", "jpeg", "png"])

    # Text input for question
    question = st.text_input("Enter a Question")

    if uploaded_image is not None and question:
        # Display uploaded image
        st.image(uploaded_image, caption="Uploaded Image", use_column_width=True)

        # Convert uploaded image to bytes
        image_bytes = uploaded_image.getvalue()

        # Get answer from image and question
        answer = get_answer(image_bytes, question)

        # Display answer
        st.subheader("Answer:")
        st.write(answer)

# Run the app
if __name__ == "__main__":
    main()







